### ISSUE TITLE
Detect darwin ARM64 platform

### ISSUE THREAD

**Issue by passsy** [onepub-dev/dcli#185]
https://github.com/noojee/dcli/blob/ff70a59d32c93cd8b4704ff919de4c7101e1760b/dcli/lib/src/script/dart_sdk.dart#L405-L428

dcli doesn't download the arm64 version of the sdk [dartsdk-macos-arm64-release.zip](https://storage.googleapis.com/dart-archive/channels/stable/release/2.15.1/sdk/dartsdk-macos-arm64-release.zip). It always downloads x64

**Comment by bsutton** [comment]
I've published a beta version of this which hopefully resolves the issue.
Can you give it a test and let me know how it goes.

The main concern is that I'm not certain what system_info returns on an arm64 bit system.

version 1.16.3-beta1

**Comment by bsutton** [comment]
@passsy did you get a chance to test this?

**Comment by bsutton** [comment]
closing out due to no response.
