### ISSUE TITLE
Terminal functions not exposed as top level functions

### ISSUE THREAD

**Issue by weenzeel** [onepub-dev/dcli#194]
According to the documentation terminal functions like clearLine should be available as top level functions.

But to use them one needs to create a local instance of the Terminal class.

**Comment by bsutton** [comment]
You are correct.
Do you have an opinion on which should be changed?

The documentation or do we expose the methods as top level functions?

I think part of the reason I put them in a class was to reduce namespace pollution but this isn' actually that much of a problem for dart.

**Comment by bsutton** [comment]
I've updated the doco to indicate that these methods are found in the Terminal class.
