### ISSUE TITLE
Documentation page doesn't work

### ISSUE THREAD

**Issue by mjablecnik** [onepub-dev/dcli#196]
Web pages `https://dcli.noojee.dev` and `https://noojee.dev` are not responding:
![image](https://user-images.githubusercontent.com/2686906/171961516-b946f2bf-832c-4f53-ab98-4d0dce17887c.png)

So all links in this repository are not working. 
Also in pub.dev page is information about Documentation and Homepage missing:
![image](https://user-images.githubusercontent.com/2686906/171961670-f3649180-5f8b-4c62-9659-30672a14406d.png)

**Comment by bsutton** [comment]
Thanks for the update.
I'm half way through updating the domain.

Will try to get it finished today.

New domain is dcli.onepub.dev.

**Comment by bsutton** [comment]
I've push a new release with the updated links.

**Comment by mjablecnik** [comment]
But links in README.md are not still working:
![image](https://user-images.githubusercontent.com/2686906/171997019-303f4bab-fab3-49fb-b7f2-bcee9b16cd48.png)

**Comment by bsutton** [comment]
bugger.
I've now updated them in 1.31.1.

greatly appreciate the feedback.
