### ISSUE TITLE
dart:cli not found

### ISSUE THREAD

**Issue by Rodsevich** [onepub-dev/dcli#207]
**Describe the bug**
By running a script on my VSCode IDE (on a Flutter project) I get this error

The thing is that it's deprecated as stated here: https://api.dart.dev/stable/2.18.3/dart-cli/waitFor.html

**To Reproduce**
 Start a process like 'ls'.start() on a test on a Flutter project on VSCode  
![image](https://user-images.githubusercontent.com/1907844/199177591-316877f9-5d89-4678-9e62-708b1d4de6b1.png)

**Expected behavior**
The script runs correctly without conflicts

**Logs**
: Error: Not found: 'dart:cli'
../…/util/wait_for_ex.dart:10
import 'dart:cli' as cli;
       ^

: Error: Method not found: 'waitFor'.
../…/util/wait_for_ex.dart:32
    value = cli.waitFor<T>(future);

**Run dcli doctor:**
From the cli run `dcli doctor`
```
Paste the output from dcli doctor here
```

**Additional context**

**Comment by bsutton** [comment]
You are gong to have to provide some additional details.

Can you paste the output of the dcli doctor and some sample code that reproduces the problem.

Yes waitFor is deprecated but dart devs have agreed to not remove it until the have an appropriate replacement.
This however is not your problem.

**Comment by bsutton** [comment]
closing - you can only use dcli on for a cli project.

You can use dcli_core in flutter which has a subset of the dcli commands.
