### ISSUE TITLE
Bump intl to 0.18.0

### ISSUE THREAD

**Issue by jodinathan** [onepub-dev/dcli#211]
My app can't resolve the dependencies because of `intl`. I tried to dig and fix the culprit but couldn't find dart_console2 repo.

Please bump intl =]

**Comment by bsutton** [comment]
You can add a pubspec override as a temporary fix.

What version of dart are you using?

**Comment by jodinathan** [comment]
> You can add a pubspec override as a temporary fix.

it is what I am doing =]

dart 2.19

**Comment by bsutton** [comment]
If you are in 2.19 you can try the dcli 2.x beta which I believe haa been
upgraded.

**Comment by jodinathan** [comment]
dunno if you are using another branch but it is still 0.17.0 in the master [pubspec](https://github.com/onepub-dev/dcli/blob/master/dcli/pubspec.yaml#L41)

**Comment by bsutton** [comment]
I've published 2.0 .1 which has intl 0.18.0

let me know how it goes.

**Comment by bsutton** [comment]
sorry about the late reply but the 2.0.1 release has intl 0.18.0 - I just
pulled it from pub.dev and check the pubspec.yaml
