### ISSUE TITLE
New release of `pubspec2 2.5.0` breaks all `dcli 2` versions 

### ISSUE THREAD

**Issue by Giuspepe** [onepub-dev/dcli#218]
All versions of `dcli 2` depend on `pubspec2: ^2.4.2` [(e.g. dcli 2.2.3)](https://github.com/onepub-dev/dcli/blob/f06eafca7863d05c8cb9fe5219b69c82afaf80c7/dcli/pubspec.yaml#L55)

This dependency constraint also includes the newly released `pubspec2 2.5.0`. However, there were breaking changes in `pubspec2 2.5.0` which cause all `dcli 2.x.y` to break:

```
../../../.pub-cache/hosted/pub.dev/dcli-2.2.3/lib/src/commands/lock.dart:123:36: Error: Too many positional arguments: 3 allowed, but 4 found.
Try removing the extra positional arguments.
            ExternalHostedReference(hosted.package, hosted.url, version, false)
                                   ^
../../../.pub-cache/hosted/pub.dev/pubspec2-2.5.0/lib/src/dependency.dart:151:9: Context: Found this candidate, but the arguments don't match.
  const ExternalHostedReference(this.name, this.url, this.versionConstraint,
        ^^^^^^^^^^^^^^^^^^^^^^^
``` 

This is the relevant breaking change (I haven't checked if there are any other breaking changes)

`pubspec2 2.5.0`:
`const ExternalHostedReference(this.name, this.url, this.versionConstraint, {this.verboseFormat = true});`

`pubspec2 2.4.2`:
`ExternalHostedReference(this.name, this.url, this.versionConstraint, [this.verboseFormat = true]);`

**Comment by bsutton** [comment]
I've retracted the 2.5 release of pubspec2 and will re-release as 3.x.

dcli should now work.

I will re-release pubspec2 as 3.x

appologies.
