### ISSUE TITLE
Upgrade http to >1.0.0 for dcli > 3.0.0

### ISSUE THREAD

**Issue by jxstxn1** [onepub-dev/dcli#221]
Hello,
thanks for maintaining dcli. I wanted to upgrade my application, which is using package `http`.
Since the dart 3.0 release, `http` bumped to version >1.0.0.
It would be great if dcli could support this version of `http`

**Comment by bsutton** [comment]
I've just released 3.1.0 which I believe should fix your issu.e
Feel free to re-open this issue if it doesn't.
