### ISSUE TITLE
stdio is not connected

### ISSUE THREAD

**Issue by bsutton** [onepub-dev/dcli#236]
When running pub_release from the alpha.11 build the following error is returned:

This occurs when trying to release pubspec_manager using the current package version number.

Updated pubspec.yaml version to 0.9.0
Regenerating version file at /home/bsutton/git/pubspec_manager/lib/src/version/version.g.dart
Running 'pub get' to ensure package is ready to publish
Found git project.
No pre release hooks found in /home/bsutton/git/pubspec_manager/tool/pre_release_hook
Generating release notes.
Would you like to edit the /home/bsutton/git/pubspec_manager/CHANGELOG.md notes (y/n): y
Unhandled exception:
Bad state: stdio is not connected
#0      _ProcessImpl.stdout (dart:io-patch/process_patch.dart:530:19)
#1      _startIsolate.<anonymous closure> (package:dcli/src/process/process/process_in_isolate.dart:89:26)
<asynchronous suspension>

**Comment by jifferon** [comment]
This is quite severe and brakes operation of DCLI

**Comment by bsutton** [comment]
I do actually have a partial fix on master for this issue and with a little more work it is completely fixable.
However at the moment I'm trying to deal with a bigger issue:

https://github.com/dart-lang/sdk/issues/52121

If you look at the final comment you can read about the problem.

This may mean that we have to make the dcli process calls async...

**Comment by bsutton** [comment]
this should be resolved in 4.0.1-beta.1
