### ISSUE TITLE
Starting a command never releases it after finish

### ISSUE THREAD

**Issue by jifferon** [onepub-dev/dcli#244]
**Describe the bug**
When you run any command, e.g. using string syntax:
```dart
'mason make ...'.start(
   workingDirectory: componentFolderPath,
   terminal: true,
)
```

The command runs itself fine however nothing after that command is being executed and dcli script just hangs there, until you kill it with `Control+C`.

Same dcli script worked just fine on `dcli: 3.4.0` and prior.

**To Reproduce**
Use `dcli: 4.0.1-beta.2`

**Expected behavior**
Excepting `''.start()` to work normally and execute code further after command is finished.

**Comment by bsutton** [comment]
diego, thanks for the report.
this was helpful. One of my own apps was exhibiting the same problem but I hadn't realised it was the terminal mode.

will investigate.

**Comment by bsutton** [comment]
so I think I have a fix for this, which I've pushed to master if you want
to have a play.

I'm a little concerned that I've caused another issue as one of my other
apps is now mis-behaving, will try and have a look tonight.

Brett

**Comment by bsutton** [comment]
I believe this is now fixed in beta.4

feel free to re-open if you are still having issues.

**Comment by jifferon** [comment]
Sorry for not answering to your previous message. Beta 4 actually did resolve that issue and whole flow now works flawlessly. Thank you very much 👍
