### ISSUE TITLE
The template 'simple' does not exist 

### ISSUE THREAD

**Issue by somtech123** [onepub-dev/dcli#247]
**Describe the bug**
The template 'simple' does not exist in 
**To Reproduce**
The template 'simple' does not exist in /Users/oscarchisomonyeacho/.dcli/template/script or /Users/oscarchisomonyeacho/.dcli/template/script/custom. when i run dcli create bin/script.dart

**Run dcli doctor:**
From the cli run `dcli doctor`
```
the output from dcli doctor here
``` Cli version      3.4.0                                                  

os                macos                                                  
os version        Version 14.4.1 (Build 23E224)
path separator    /                                                      

dart version      3.3.4                                                  

String: Synchronous waiting using dart:cli waitFor and C API Dart_WaitForEvent is deprecated and disabled by default. This feature will be fully removed in Dart 3.4 release. You can currently still enable it by passing --enable_deprecated_wait_for to the Dart VM. See https://dartbug.com/52121. 
Stacktrace: dart:cli                                                        waitFor
package:dcli/src/util/wait_for_ex.dart 38:17                    waitForEx
package:dcli/src/functions/which.dart 97:5                      which
package:dcli/src/util/dcli_paths.dart 42:20                     DCliPaths.pathToDCli
package:dcli/src/commands/doctor.dart 125:36                    DoctorCommand._printExePaths
package:dcli/src/commands/doctor.dart 43:5                      DoctorCommand.run
package:dcli/src/script/command_line_runner.dart 98:33          CommandLineRunner.process
package:dcli/src/script/entry_point.dart 44:44                  EntryPoint._parseCmdLine
package:dcli/src/script/entry_point.dart 38:7                   EntryPoint.process
../../.pub-cache/hosted/pub.dev/dcli-3.4.0/bin/dcli.dart 17:41  DCli.run
../../.pub-cache/hosted/pub.dev/dcli-3.4.0/bin/dcli.dart 12:16  main
dart:isolate                                                    _RawReceivePort._handleMessage
package:dcli/src/util/wait_for_ex.dart 35:28                    waitForEx
package:dcli/src/functions/which.dart 97:5                      which
package:dcli/src/util/dcli_paths.dart 42:20                     DCliPaths.pathToDCli
package:dcli/src/commands/doctor.dart 125:36                    DoctorCommand._printExePaths
package:dcli/src/commands/doctor.dart 43:5                      DoctorCommand.run
package:dcli/src/script/command_line_runner.dart 98:33          CommandLineRunner.process
package:dcli/src/script/entry_point.dart 44:44                  EntryPoint._parseCmdLine
package:dcli/src/script/entry_point.dart 38:7                   EntryPoint.process
../../.pub-cache/hosted/pub.dev/dcli-3.4.0/bin/dcli.dart 17:41  DCli.run
../../.pub-cache/hosted/pub.dev/dcli-3.4.0/bin/dcli.dart 12:16  main




**Additional context**
Add any other context about the problem here.

**Comment by bsutton** [comment]
Have you run dcli_install?

You should also be running the beta version of 4.x given the dart version
you are using.

**Comment by somtech123** [comment]
yes, but it giving me an  Synchronous waiting using dart:cli waitFor and C API Dart_WaitForEvent is deprecated and disabled by default. and adding --enable_deprecated_wait_for does not install it

**Comment by bsutton** [comment]
Which is why you need to use the dcli 4.x beta which is all about fixing
the wait for issue.

**Comment by somtech123** [comment]
okay, how do i install the dcli 4.x beta there is documentation on how to migrate  to 4.x on pub.dev

**Comment by somtech123** [comment]
i'm getting an error when i run  dart pub global activate dcli_sdk  
Failed to build dcli_sdk:dcli_complete:
../../.pub-cache/hosted/pub.dev/dcli_sdk-1.0.0/lib/src/commands/lock.dart:107:3: Error: Type 'DependencyGitBuilder' not found.
  DependencyGitBuilder buildGit(GitPackageDependency git) =>
  ^^^^^^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/dcli_sdk-1.0.0/lib/src/commands/compile.dart:256:33: Error: The type 'Executables' used in the 'for' loop must implement 'Iterable<dynamic>'.
 - 'Executables' is from 'package:pubspec_manager/src/pubspec/internal_parts.dart' ('../../.pub-cache/hosted/pub.dev/pubspec_manager-1.0.0/lib/src/pubspec/internal_parts.dart').
 - 'Iterable' is from 'dart:core'.
      for (final exe in pubspec.executables) {
                                ^
../../.pub-cache/hosted/pub.dev/dcli_sdk-1.0.0/lib/src/commands/lock.dart:80:30: Error: The method 'append' isn't defined for the class 'Dependencies'.
 - 'Dependencies' is from 'package:pubspec_manager/src/pubspec/internal_parts.dart' ('../../.pub-cache/hosted/pub.dev/pubspec_manager-1.0.0/lib/src/pubspec/internal_parts.dart').
Try correcting the name to the name of an existing method, or defining a method named 'append'.
        pubspec.dependencies.append(package.iswitch(
                             ^^^^^^
../../.pub-cache/hosted/pub.dev/dcli_sdk-1.0.0/lib/src/commands/lock.dart:108:7: Error: The method 'DependencyGitBuilder' isn't defined for the class 'LockCommand'.
 - 'LockCommand' is from 'package:dcli_sdk/src/commands/lock.dart' ('../../.pub-cache/hosted/pub.dev/dcli_sdk-1.0.0/lib/src/commands/lock.dart').
Try correcting the name to the name of an existing method, or defining a method named 'DependencyGitBuilder'.
      DependencyGitBuilder(
      ^^^^^^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/dcli_sdk-1.0.0/lib/src/commands/lock.dart:118:14: Error: The method 'DependencyPubHostedBuilder' isn't defined for the class 'LockCommand'.
 - 'LockCommand' is from 'package:dcli_sdk/src/commands/lock.dart' ('../../.pub-cache/hosted/pub.dev/dcli_sdk-1.0.0/lib/src/commands/lock.dart').
Try correcting the name to the name of an existing method, or defining a method named 'DependencyPubHostedBuilder'.
      return DependencyPubHostedBuilder(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/dcli_sdk-1.0.0/lib/src/commands/lock.dart:121:14: Error: The method 'DependencyAltHostedBuilder' isn't defined for the class 'LockCommand'.
 - 'LockCommand' is from 'package:dcli_sdk/src/commands/lock.dart' ('../../.pub-cache/hosted/pub.dev/dcli_sdk-1.0.0/lib/src/commands/lock.dart').
Try correcting the name to the name of an existing method, or defining a method named 'DependencyAltHostedBuilder'.
      return DependencyAltHostedBuilder(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/dcli_sdk-1.0.0/lib/src/commands/lock.dart:130:7: Error: The method 'DependencyPathBuilder' isn't defined for the class 'LockCommand'.
 - 'LockCommand' is from 'package:dcli_sdk/src/commands/lock.dart' ('../../.pub-cache/hosted/pub.dev/dcli_sdk-1.0.0/lib/src/commands/lock.dart').
Try correcting the name to the name of an existing method, or defining a method named 'DependencyPathBuilder'.
      DependencyPathBuilder(name: path.package, path: path.path);
      ^^^^^^^^^^^^^^^^^^^^^
Failed to build dcli_sdk:dcli_install:
../../.pub-cache/hosted/pub.dev/dcli_sdk-1.0.0/lib/src/commands/lock.dart:107:3: Error: Type 'DependencyGitBuilder' not found.
  DependencyGitBuilder buildGit(GitPackageDependency git) =>
  ^^^^^^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/dcli_sdk-1.0.0/lib/src/commands/compile.dart:256:33: Error: The type 'Executables' used in the 'for' loop must implement 'Iterable<dynamic>'.
 - 'Executables' is from 'package:pubspec_manager/src/pubspec/internal_parts.dart' ('../../.pub-cache/hosted/pub.dev/pubspec_manager-1.0.0/lib/src/pubspec/internal_parts.dart').
 - 'Iterable' is from 'dart:core'.
      for (final exe in pubspec.executables) {
                                ^
../../.pub-cache/hosted/pub.dev/dcli_sdk-1.0.0/lib/src/commands/lock.dart:80:30: Error: The method 'append' isn't defined for the class 'Dependencies'.
 - 'Dependencies' is from 'package:pubspec_manager/src/pubspec/internal_parts.dart' ('../../.pub-cache/hosted/pub.dev/pubspec_manager-1.0.0/lib/src/pubspec/internal_parts.dart').
Try correcting the name to the name of an existing method, or defining a method named 'append'.
        pubspec.dependencies.append(package.iswitch(
                             ^^^^^^
../../.pub-cache/hosted/pub.dev/dcli_sdk-1.0.0/lib/src/commands/lock.dart:108:7: Error: The method 'DependencyGitBuilder' isn't defined for the class 'LockCommand'.
 - 'LockCommand' is from 'package:dcli_sdk/src/commands/lock.dart' ('../../.pub-cache/hosted/pub.dev/dcli_sdk-1.0.0/lib/src/commands/lock.dart').
Try correcting the name to the name of an existing method, or defining a method named 'DependencyGitBuilder'.
      DependencyGitBuilder(
      ^^^^^^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/dcli_sdk-1.0.0/lib/src/commands/lock.dart:118:14: Error: The method 'DependencyPubHostedBuilder' isn't defined for the class 'LockCommand'.
 - 'LockCommand' is from 'package:dcli_sdk/src/commands/lock.dart' ('../../.pub-cache/hosted/pub.dev/dcli_sdk-1.0.0/lib/src/commands/lock.dart').
Try correcting the name to the name of an existing method, or defining a method named 'DependencyPubHostedBuilder'.
      return DependencyPubHostedBuilder(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/dcli_sdk-1.0.0/lib/src/commands/lock.dart:121:14: Error: The method 'DependencyAltHostedBuilder' isn't defined for the class 'LockCommand'.
 - 'LockCommand' is from 'package:dcli_sdk/src/commands/lock.dart' ('../../.pub-cache/hosted/pub.dev/dcli_sdk-1.0.0/lib/src/commands/lock.dart').
Try correcting the name to the name of an existing method, or defining a method named 'DependencyAltHostedBuilder'.
      return DependencyAltHostedBuilder(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/dcli_sdk-1.0.0/lib/src/commands/lock.dart:130:7: Error: The method 'DependencyPathBuilder' isn't defined for the class 'LockCommand'.
 - 'LockCommand' is from 'package:dcli_sdk/src/commands/lock.dart' ('../../.pub-cache/hosted/pub.dev/dcli_sdk-1.0.0/lib/src/commands/lock.dart').
Try correcting the name to the name of an existing method, or defining a method named 'DependencyPathBuilder'.
      DependencyPathBuilder(name: path.package, path: path.path);
      ^^^^^^^^^^^^^^^^^^^^^
Failed to build dcli_sdk:dcli:
../../.pub-cache/hosted/pub.dev/dcli_sdk-1.0.0/lib/src/commands/lock.dart:107:3: Error: Type 'DependencyGitBuilder' not found.
  DependencyGitBuilder buildGit(GitPackageDependency git) =>
  ^^^^^^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/dcli_sdk-1.0.0/lib/src/commands/compile.dart:256:33: Error: The type 'Executables' used in the 'for' loop must implement 'Iterable<dynamic>'.
 - 'Executables' is from 'package:pubspec_manager/src/pubspec/internal_parts.dart' ('../../.pub-cache/hosted/pub.dev/pubspec_manager-1.0.0/lib/src/pubspec/internal_parts.dart').
 - 'Iterable' is from 'dart:core'.
      for (final exe in pubspec.executables) {
                                ^
../../.pub-cache/hosted/pub.dev/dcli_sdk-1.0.0/lib/src/commands/lock.dart:80:30: Error: The method 'append' isn't defined for the class 'Dependencies'.
 - 'Dependencies' is from 'package:pubspec_manager/src/pubspec/internal_parts.dart' ('../../.pub-cache/hosted/pub.dev/pubspec_manager-1.0.0/lib/src/pubspec/internal_parts.dart').
Try correcting the name to the name of an existing method, or defining a method named 'append'.
        pubspec.dependencies.append(package.iswitch(
                             ^^^^^^
../../.pub-cache/hosted/pub.dev/dcli_sdk-1.0.0/lib/src/commands/lock.dart:108:7: Error: The method 'DependencyGitBuilder' isn't defined for the class 'LockCommand'.
 - 'LockCommand' is from 'package:dcli_sdk/src/commands/lock.dart' ('../../.pub-cache/hosted/pub.dev/dcli_sdk-1.0.0/lib/src/commands/lock.dart').
Try correcting the name to the name of an existing method, or defining a method named 'DependencyGitBuilder'.
      DependencyGitBuilder(
      ^^^^^^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/dcli_sdk-1.0.0/lib/src/commands/lock.dart:118:14: Error: The method 'DependencyPubHostedBuilder' isn't defined for the class 'LockCommand'.
 - 'LockCommand' is from 'package:dcli_sdk/src/commands/lock.dart' ('../../.pub-cache/hosted/pub.dev/dcli_sdk-1.0.0/lib/src/commands/lock.dart').
Try correcting the name to the name of an existing method, or defining a method named 'DependencyPubHostedBuilder'.
      return DependencyPubHostedBuilder(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/dcli_sdk-1.0.0/lib/src/commands/lock.dart:121:14: Error: The method 'DependencyAltHostedBuilder' isn't defined for the class 'LockCommand'.
 - 'LockCommand' is from 'package:dcli_sdk/src/commands/lock.dart' ('../../.pub-cache/hosted/pub.dev/dcli_sdk-1.0.0/lib/src/commands/lock.dart').
Try correcting the name to the name of an existing method, or defining a method named 'DependencyAltHostedBuilder'.
      return DependencyAltHostedBuilder(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/dcli_sdk-1.0.0/lib/src/commands/lock.dart:130:7: Error: The method 'DependencyPathBuilder' isn't defined for the class 'LockCommand'.
 - 'LockCommand' is from 'package:dcli_sdk/src/commands/lock.dart' ('../../.pub-cache/hosted/pub.dev/dcli_sdk-1.0.0/lib/src/commands/lock.dart').
Try correcting the name to the name of an existing method, or defining a method named 'DependencyPathBuilder'.
      DependencyPathBuilder(name: path.package, path: path.path);
      ^^^^^^^^^^^^^^^^^^^^^

**Comment by bsutton** [comment]
dart pub global activate dcli 4.0.1-beta.4

**Comment by bsutton** [comment]
Sorry dcl_sdk not dcli.

**Comment by somtech123** [comment]
okay i've gotten the dependency with dart pub global activate dcli 4.0.1-beta.4, can i still install it with sudo dcli install

**Comment by bsutton** [comment]
Did you try?
dart pub global activate dcli_sdk 4.0.1-beta.4 --overwrite

FYI: I'm looking to get the 4.0 release out to day which should completely resolve this issue.

**Comment by bsutton** [comment]
4.0.0 has been released which will have resolved this issue.

If you have further problems please open a new issue.
