### ISSUE TITLE
URGENT dcli_sdk uses outdated win32 version

### ISSUE THREAD

**Issue by wolframm** [onepub-dev/dcli#251]
With the latest Dart 3.5 release, `dcli_sdk` can no longer be installed using `dart pub global activate dcli_sdk` due to its outdated `win32` package version. 

Please urgently release a new version using `win32: ^5.0.0`.

**Comment by bsutton** [comment]
I have a fix ready.

Will look to release it tomorrow.

**Comment by bsutton** [comment]
dcli 6.0 has been released with a fix.
