### ISSUE TITLE
dshell install permission issues

### ISSUE THREAD

**Issue by andresaraujo** [onepub-dev/dcli#45]
I'm trying to install dshell in mac OS Mojave, but I get an `Dart SDK not found! of type _Exception` error, seems that `_detect` method doesn't support mac OS.

**Comment by bsutton** [comment]
Can you provide details of what you where doing?

**Comment by dennougorilla** [comment]
same error
```
dshell: Exception occured: FileSystemException: Deletion failed, path = '/Users/dennougorilla/.dshell/cache' (OS Error: Permission denied, errno = 13) of type DShellException
dshell: Stacktrace: waitForEx.dart : waitForEx : 37
project_cache.dart : ProjectCache.cleanAll : 91
clean_all.dart : CleanAllCommand.run : 12
install.dart : InstallCommand.run : 73
command_line_runner.dart : CommandLineRunner.process : 81
entry_point.dart : EntryPoint._parseCmdLine : 37
entry_point.dart : EntryPoint.process : 31
dshell.dart : DShell.run : 9
dshell.dart : main : 4
isolate_patch.dart : _startIsolate.<anonymous closure> : 305
```

**Comment by bsutton** [comment]
So what is the permissions the .dshell directory?

Did you run the install using sudo?

**Comment by bsutton** [comment]
I've just released a new dev release of dshell:

dshell: ^1.1.0-dev.1

Can you install the new version and then from the cli run:

```
dshell doctor
```

Then paste the output here.

**Comment by bsutton** [comment]
FYI to install a dev version run:

```
pub global activate dshell 1.1.0-dev.1
```

**Comment by andresaraujo** [comment]
Using `dshell 1.1.0-dev.1` got the same permission issue when trying to run dshell create or trying to run the script. (I ran dshell install with sudo).

```
dshell: Exception occured: FileSystemException: Creation failed, path = '/Users/myusername/.dshell/cache/Users' (OS Error: Permission denied, errno = 13) of type FileSystemException
dshell: Stacktrace: directory_impl.dart : _Directory.createSync : 140
directory_impl.dart : _Directory.createSync : 135
directory_impl.dart : _Directory.createSync : 135
directory_impl.dart : _Directory.createSync : 135
directory_impl.dart : _Directory.createSync : 135
directory_impl.dart : _Directory.createSync : 135
file_helper.dart : createDir : 24
virtual_project.dart : VirtualProject.createProject : 81
project_cache.dart : ProjectCache.createProject : 70
create.dart : CreateCommand.run : 29
```

Permissions
```
.dshell   : rwxr-xr-x 6:myusername   /Users/myusername/.dshell
cache     : rwxr-xr-x 2:root   /Users/myusername/.dshell/cache
dependencies.yaml: rw-r--r-- 1:myusername   /Users/myusername/.dshell/dependencies.yaml
templates : rwxr-xr-x 2:myusername   /Users/myusername/.dshell/templates
```

**Comment by andresaraujo** [comment]
ok I wiped out the `.dshell` directory and reintalled the dev.1 version then `sudo dshell install`, now got this:

```
dshell: Exception occured: FileSystemException: Cannot open file, path = '/etc/path.d/dshell' (OS Error: No such file or directory, errno = 2) of type FileSystemException
dshell: Stacktrace: file_impl.dart : _File.throwIfError : 645
file_impl.dart : _File.openSync : 489
file_sync.dart : FileSync._open : 26
file_sync.dart : new FileSync : 20
string_as_process.dart : StringAsProcess.write : 188
install.dart : InstallCommand.addBinToPath : 141
install.dart : InstallCommand.run : 83
command_line_runner.dart : CommandLineRunner.process : 81
entry_point.dart : EntryPoint._parseCmdLine : 37
entry_point.dart : EntryPoint.process : 31
```

Will try to figure out over the weekend when I have some free time

**Comment by bsutton** [comment]
Delete the .dshell directory and run dshell install without sudo.

**Comment by bsutton** [comment]
This looks like a bug in 1.1 can you send me the dshell doctor output.

**Comment by bsutton** [comment]
I think I've worked out the problem.
I've pushed a fix in 1.1.1-dev.1.

Can you give it a test. Unfortunately I don't have access to mac for testing.

pub global activate dshell 1.1.1-dev.1

**Comment by andresaraujo** [comment]
Thanks @bsutton, I got it working (in 1.1.0+).

The issue was that if your run `dshell install` with sudo you will need to run every command with sudo. The work around is to delete `.dshell/` directory and just export the bin file after `dshell install` (without sudo):

1. `pub global activate dshell`
2. Add dshell bin directory to your `.bashrc/.zshrc`:

```
export PATH="$PATH":"$HOME/.dshell/bin"
```

3. You can run dshell commands and scripts without an issue

**Comment by bsutton** [comment]
Dshell should add itself to the path when running the install.
The doco I found on a Mac was to add a file into /etc/path.d.

It's this not the case?

**Comment by bsutton** [comment]
closing as no response.
