### ISSUE TITLE
brew install dshell

### ISSUE THREAD

**Issue by wstrange** [onepub-dev/dcli#55]
First - I have to say this is ultra cool. Very clever.

Consider this a low priority feature request. I was thinking of how to increase adoption of dshell to folks who have not drunk the Dart  kool-aid ;-)  Having to install Dart, and use `pub global activate` might be too much friction.

Would it be possible to `brew install dshell` ?  I think brew supports dependenices, so you could install the Dart VM at the same time. 

I guess the hard part is the package dependencies for dshell programs that use extra packages.  Perhaps the out of box dshell would have enough built-ins for most use cases.

**Comment by bsutton** [comment]
I've actually built a dart exe dshell_install which installs dart and
dshell for apt based system.

I've had a bit of a play with building a snap to install it but I'm not at
all familiar with home brew (is that a mac thing).
If interested in getting involved I'm happy to support your efforts.

I've plans to extend dshell_install to also work for a mac but wrapping it
in something like home brew would make installations more palatable (no
body likes downloading a raw exe).

**Comment by bsutton** [comment]
I think this is beyond the resources we have and really duplicates the dart times page on installing dart on a variety of OSs.
